# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVE2QqyEz4QqJG_eDDO_2O5LWIaMmNXb
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Page Configuration
st.set_page_config(page_title="Global GHG Emissions Explorer", layout="wide")

# 2. Data Loading
@st.cache_data
def load_data():
    file_path = 'OECD.ENV.EPI,DSD_AIR_GHG@DF_AIR_GHG,+.A.GHG._T.KG_CO2E_PS.csv'
    df = pd.read_csv(file_path)
    df['TIME_PERIOD'] = pd.to_numeric(df['TIME_PERIOD'], errors='coerce')
    df['Observation value'] = pd.to_numeric(df['Observation value'], errors='coerce')
    df = df.dropna(subset=['TIME_PERIOD', 'Observation value', 'Reference area'])
    return df

try:
    df = load_data()
except Exception as e:
    st.error(f"Error loading file: {e}")
    st.stop()

# --- Sidebar ---
st.sidebar.header("Filters")
all_countries = sorted(df['Reference area'].unique().tolist())
default_options = [c for c in all_countries if any(x in c for x in ['United Kingdom', 'United States', 'Australia'])]
if not default_options:
    default_options = all_countries[:3]

selected_countries = st.sidebar.multiselect("Select Countries", options=all_countries, default=default_options)
year_range = st.sidebar.slider("Select Year", int(df['TIME_PERIOD'].min()), int(df['TIME_PERIOD'].max()), (2000, int(df['TIME_PERIOD'].max())))

# Filtering
filtered_df = df[(df['Reference area'].isin(selected_countries)) & (df['TIME_PERIOD'].between(year_range[0], year_range[1]))]

# --- Main Interface ---
st.title("🌍 Global GHG Emissions Tracker")

st.subheader("1. Emissions Trend Over Time")
if not filtered_df.empty:
    fig_line = px.line(filtered_df, x='TIME_PERIOD', y='Observation value', color='Reference area', template="plotly_white")
    # 注意：这里改成了新版的 width="stretch"
    st.plotly_chart(fig_line, width="stretch")
else:
    st.info("Please select countries in the sidebar.")

st.subheader(f"2. Comparison for the Year {year_range[1]}")
df_snapshot = df[(df['TIME_PERIOD'] == year_range[1]) & (df['Reference area'].isin(selected_countries))]
if not df_snapshot.empty:
    fig_bar = px.bar(df_snapshot.sort_values('Observation value'), x='Reference area', y='Observation value', color='Observation value')
    # 同样修改此处
    st.plotly_chart(fig_bar, width="stretch")

# --- Write-up ---
st.divider()
st.header("Project Write-up")
st.write("**Question:** How do emissions vary per capita across nations?")
st.write("**Rationale:** Line charts show trends; Bar charts show rankings. Sidebar filters allow deep dives into specific regions.")